---
title: "Lab 7 Assignment: Group 28"
format:
  html:
    embed-resources: true
editor: visual
execute: 
  warning: false
---

# Attila

## Libraries

```{r}
library(tidyverse)
```

## New analysis

Something something.
```{r}
xy <- seq(from = -3,
          to = 3, 
          by = 0.01)
expand.grid(x = xy,
            y = xy) |>
  ggplot(
    mapping = aes(
      x = (1 - x - sin(y^2)),
      y = (1 + y - cos(x^2)))) +
  geom_point(alpha = 0.05,
             shape = 20,
             size = 0) +
  theme_void() +
  coord_polar()
```

Test_2 asdf asdf

# Karo

If in trouble, close and refresh.

```{r}
dir_name <- "./"
fun_read <- "retire_statistical_significance.pdf"
fun_url <- "https://www.nature.com/articles/d41586-019-00857-9.pdf"
download.file(
    url = fun_url,
    destfile = fun_read)
```

## New feature

I have no ideas for code. Let's just move it forward...

# Taner

The final edit

## New Feature

some text :)

```{r}

```

# Marty

This is my edit

```{r}
x <- tibble(test_data = rnorm(100, mean = 0, sd = 1))
x
marty_plot <- x |>
  ggplot(aes(test_data)) +
  geom_density()
marty_plot
```

# Jiawen

Late catching up...

```{r}
variable <- 1
```

